export default [
  {
    type: 'School Room',
    name: 'Evolution',
    imageSrc: 'https://source.unsplash.com/random/?hotel',
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
    showItems: true,
    color: ''
  },
  {
    type: 'Banquet',
    name: 'Evolution',
    imageSrc: 'https://source.unsplash.com/random/?hotel',
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
    showItems: true,
  },
  {
    type: 'Reception',
    name: 'Evolution',
    imageSrc: 'https://source.unsplash.com/random/?hotel',
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
    showItems: true,
  },
  {
    type: 'Theatre',
    name: 'Evolution',
    imageSrc: 'https://source.unsplash.com/random/?hotel',
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
    showItems: true,
  },
  {
    type: 'U-Shape',
    name: 'Evolution',
    imageSrc: 'https://source.unsplash.com/random/?hotel',
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
    showItems: true,
  },
]
