export { default as AnimatedHero } from './AnimatedHero'
export { default as AnimatedHero_v2 } from './AnimatedHero_v2'
export { default as StyledHero } from './StyledHero'
export { default as Hero } from './Hero'
export { default as HeroII } from './HeroII'
