export default [
  {
    title:'School',
    type: 'School Room',
    name: 'Evolution',
    image: {
      variant: 'smallHorizontal',
      src: 'https://source.unsplash.com/random/?hotel',
    },
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
  },
  {
    type: 'School Room',
    name: 'Evolution',
    image: {
      variant: 'smallHorizontal',
      src: 'https://source.unsplash.com/random/?hotel',
    },
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
  },
  {
    type: 'School Room',
    name: 'Evolution',
    image: {
      variant: 'smallHorizontal',
      src: 'https://source.unsplash.com/random/?hotel',
    },
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
  },
  {
    type: 'School Room',
    name: 'Evolution',
    image: {
      variant: 'smallHorizontal',
      src: 'https://source.unsplash.com/random/?hotel',
    },
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
  },
  {
    type: 'Banquet',
    name: 'Evolution',
    image: {
      variant: 'smallHorizontal',
      src: 'https://source.unsplash.com/random/?hotel',
    },
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
  },
  {
    type: 'Banquet',
    name: 'Evolution',
    image: {
      variant: 'smallHorizontal',
      src: 'https://source.unsplash.com/random/?hotel',
    },
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
  },
  {
    type: 'Banquet',
    name: 'Evolution',
    image: {
      variant: 'smallHorizontal',
      src: 'https://source.unsplash.com/random/?hotel',
    },
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
  },
  {
    type: 'Reception',
    name: 'Evolution',
    image: {
      variant: 'smallHorizontal',
      src: 'https://source.unsplash.com/random/?hotel',
    },
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
  },
  {
    type: 'Reception',
    name: 'Evolution',
    image: {
      variant: 'smallHorizontal',
      src: 'https://source.unsplash.com/random/?hotel',
    },
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
  },
  {
    type: 'Theatre',
    name: 'Evolution',
    image: {
      variant: 'smallHorizontal',
      src: 'https://source.unsplash.com/random/?hotel',
    },
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
  },
  {
    type: 'U-Shape',
    name: 'Evolution',
    image: {
      variant: 'smallHorizontal',
      src: 'https://source.unsplash.com/random/?hotel',
    },
    subtitle: '13M X 7M',
    sq_M: '129M',
    guests: '32',
    href: '/',
  },
]
