name: Quality

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install    
      - name: Test
        run: npm run test:coverage
        env:
          CI: true
      - name: Generate build
        run: npm run build-storybook
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: hotel-ui-artifact
          path: build